//! Auto-generated Steam protobuf types.
//!
//! Generated by `prost-build` from the SteamDatabase/Protobufs repository.
//! See `build.rs` for compilation details.

// Include the generated file from prost-build
include!(concat!(env!("OUT_DIR"), "/_.rs"));
