import type { PluginSdk } from "sdk";

export type { PluginSdk } from "sdk";
export type {
  BiliComment,
  BiliCommentContent,
  BiliCommentMember,
  BiliCommentPage,
  BiliCommentSort,
  BiliDanmakuItem,
  BiliDynamicCard,
  BiliDynamicCreated,
  BiliDynamicForwardEntry,
  BiliDynamicForwardsPage,
  BiliDynamicLive,
  BiliDynamicPage,
  BiliDynamicVideo,
  BiliErrorDto,
  BiliErrorKind,
  BiliFavoriteFolder,
  BiliFavoriteItem,
  BiliHistoryItem,
  BiliHotWord,
  BiliOwner,
  BiliOwnerInteractionState,
  BiliLoginInfo,
  BiliLocalProgress,
  BiliOperationResult,
  BiliPlaybackSource,
  BiliQualityOption,
  BiliQrLoginKey,
  BiliQrLoginStatus,
  BiliReportReason,
  BiliSdkError,
  BiliToViewItem,
  BiliUserSpace,
  BiliVideoCard,
  BiliVideoDetail,
  BiliVideoInteractionState,
  BiliVideoInteractionStats,
  BiliVideoPage,
  BiliVideoStats,
  BiliWeeklySeries,
  BiliBangumiFollow,
  BiliPgcCard,
  BiliPgcSection,
  BiliPreciousVideos,
  BiliSeasonDetail,
  BiliSeasonEpisode,
} from "sdk";

export interface BilibiliRuntime {
  sdk: PluginSdk | null;
  disposed: boolean;
}
